### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by yaya-sy** [Dereck0602/Bolaco#1]
Hi, thank you for sharing your work. Very interesting!

Which metrics do you use for zero-shot evaluation? `lm-evaluation-harness` proposes two metrics and I was wondering which one you use.

Thank you a lot.

**Comment by Dereck0602** [comment]
Hi! We report acc_norm for hellaswag, arc_challenge and openbookqa, and report acc for others.

**Comment by yaya-sy** [comment]
Thank you very much!
